project:
  type: book

book:
  title: "SISMID Module 2 Materials (2023)"
  subtitle: "Mathematical Models of Infectious Diseases"
  author:
    - name: "Callum Arnold"
      url: https://callumarnold.com
      affiliation: Pennsylvania State University
      orcid: 0000-0002-3245-6956
  date: "6/07/2023"
  chapters:
    - index.qmd
    - part: "Pre-Requisites"
      chapters:
        - exercise-requirements.qmd
        - install-r.qmd
        - just-enough-rstudio.qmd
        - just-enough-r.qmd
        - project-management.qmd
    - part: "Day 1"
      chapters: 
        - L01_intro-to-modeling.qmd
        - L02_sir-basics.qmd
        - r-session-01.qmd
        - L03_hit-and-vaccinations.qmd
    - part: "Day 2"
      chapters: 
        - L04_heterogeneity.qmd
        - L05_age-structure.qmd
        - r-session-02.qmd
        - L06_parameter-estimation.qmd
        - r-session-03.qmd
    - part: "Day 3"
      chapters: 
        - L07_models-and-data.qmd
        - L08_stochastic-models.qmd
    - references.qmd
  repo-url: https://github.com/arnold-c/SISMID-Module-02_2023
  repo-actions: [edit]
  sidebar:
    logo: ./images/sismid2023-logo-green.png
    search: true
    border: true
    pinned: true
  reader-mode: true
  favicon: ./images/sismid2023-logo-green.png

# Default for table of contents
toc: true
toc-title: Page Items
toc-location: right

# Default knitr options
execute:
  echo: true
  message: true
  warning: true
  cache: true

# Default author
author:
  - name: Callum Arnold
    url: https://callumarnold.com
    affiliation: Pennsylvania State University
    orcid: 0000-0002-3245-6956

# Default fields for citation
citation: true
license: "CC BY-NC"

bibliography: SISMID-Module-2.bib

crossref:
  chapters: true

format:
  html:
    theme:
      light: [cosmo, format/_fonts.scss, format/_light.scss, format/_callouts.scss]
      dark: [cosmo, format/_fonts.scss, format/_dark.scss, format/_callouts.scss]
    grid:
      sidebar-width: 270px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1rem
    code-copy: true
    code-fold: show
    code-overflow: wrap
    code-link: true
    code-tools: true
    code-line-numbers: true

# Extension Lua filters
filters:
  - line-highlight
